name: Test Docker Build

on:
  pull_request:

jobs:
  find-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.find-paths.outputs.paths }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Find Dockerfile paths
        id: find-paths
        run: |
          paths=$(find Dockerfiles -name Dockerfile -type f | jq -R -s -c 'split("\n")[:-1]')
          echo "paths=$paths" >> $GITHUB_OUTPUT

  test-build:
    needs: find-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.find-dockerfiles.outputs.paths) }}
      fail-fast: false
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get image name
        id: image-name
        run: |
          name=$(dirname ${{ matrix.dockerfile }} | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/$(dirname ${{ matrix.dockerfile }})
          push: false
          load: true
          tags: test-${{ steps.image-name.outputs.name }}:${{ github.sha }}

      - name: Test container starts
        run: |
          docker run --rm test-${{ steps.image-name.outputs.name }}:${{ github.sha }} --version
          if [ $? -ne 0 ]; then
            echo "Container failed to start properly"
            exit 1
          fi
