name: Build and Publish Runner Image

on:
  schedule:
    - cron: '0 14 * * *' # Run once per day at 2 PM UTC


  push:
    branches:
      - main
    paths:
      - 'Dockerfiles/Runner/Dockerfile'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: gh_hdc-runner
  FULL_IMAGE_NAME: ${{ github.repository_owner }}/public-docker/gh_hdc-runner

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.FULL_IMAGE_NAME }}
          tags: |
            # Always include latest tag
            type=raw,value=latest
            # Include semver tags
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # Include git sha for tracking
            type=sha,format=long

      # Debug step to show what tags will be used
      - name: Debug metadata
        run: |
          echo "All tags that will be used:"
          echo "${{ steps.meta.outputs.tags }}"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          default_bump: patch
          create_annotated_tag: true
          tag_prefix: v
          
      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: Dockerfiles/Runner
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,new=true
          provenance: true

      # Debug step to inspect the built image
      - name: Debug image info
        run: |
          echo "Built image digest:"
          echo "${{ steps.build_push.outputs.digest }}"
          echo "All tags pushed:"
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.FULL_IMAGE_NAME }}:latest
