name: Build and Publish Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # every 4 hours
  push:
    branches: [main]
    paths:
      - 'Dockerfiles/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.discover.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Discover Dockerfiles
        id: discover
        run: |
          files=$(find Dockerfiles -mindepth 2 -maxdepth 2 -name Dockerfile)
          matrix=$(echo "$files" | jq -R -s -c 'split("\n")[:-1] | {dockerfile: .}')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build-matrix:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-and-push.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image name and context
        id: meta
        run: |
          context_path=$(dirname "${{ matrix.dockerfile }}")
          image_name=$(echo "$context_path" | sed 's|^Dockerfiles/||' | tr '/.' '-' | tr '[:upper:]' '[:lower:]')
          if [[ -z "$image_name" ]]; then image_name="docker"; fi
          echo "context_path=$context_path" >> $GITHUB_OUTPUT
          echo "image_name=$image_name" >> $GITHUB_OUTPUT

      - name: Set tags
        id: tags
        run: |
          echo "tags=${{ env.REGISTRY }}/${{ github.repository_owner }}/public-docker/${{ steps.meta.outputs.image_name }}:latest,${{ env.REGISTRY }}/${{ github.repository_owner }}/public-docker/${{ steps.meta.outputs.image_name }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "${{ steps.meta.outputs.context_path }}"
          file: "${{ matrix.dockerfile }}"
          push: true
          tags: "${{ steps.tags.outputs.tags }}"

      - name: Show Image Info
        run: |
          echo "Image: ${{ steps.tags.outputs.tags }}"
